#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("UMeng.Social.Resource", IsApplication=false)]

namespace UMeng.Social
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public static int umeng_socialize_fade_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int umeng_socialize_fade_out = 2130968577;
			
			// aapt resource value: 0x7f040002
			public static int umeng_socialize_shareboard_animation_in = 2130968578;
			
			// aapt resource value: 0x7f040003
			public static int umeng_socialize_shareboard_animation_out = 2130968579;
			
			// aapt resource value: 0x7f040004
			public static int umeng_socialize_slide_in_from_bottom = 2130968580;
			
			// aapt resource value: 0x7f040005
			public static int umeng_socialize_slide_out_from_bottom = 2130968581;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060001
			public static int umeng_socialize_color_group = 2131099649;
			
			// aapt resource value: 0x7f060000
			public static int umeng_socialize_comments_bg = 2131099648;
			
			// aapt resource value: 0x7f060004
			public static int umeng_socialize_divider = 2131099652;
			
			// aapt resource value: 0x7f06000b
			public static int umeng_socialize_edit_bg = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public static int umeng_socialize_grid_divider_line = 2131099660;
			
			// aapt resource value: 0x7f060003
			public static int umeng_socialize_list_item_bgcolor = 2131099651;
			
			// aapt resource value: 0x7f060002
			public static int umeng_socialize_list_item_textcolor = 2131099650;
			
			// aapt resource value: 0x7f060007
			public static int umeng_socialize_text_friends_list = 2131099655;
			
			// aapt resource value: 0x7f060008
			public static int umeng_socialize_text_share_content = 2131099656;
			
			// aapt resource value: 0x7f060005
			public static int umeng_socialize_text_time = 2131099653;
			
			// aapt resource value: 0x7f060006
			public static int umeng_socialize_text_title = 2131099654;
			
			// aapt resource value: 0x7f06000a
			public static int umeng_socialize_text_ucenter = 2131099658;
			
			// aapt resource value: 0x7f060009
			public static int umeng_socialize_ucenter_bg = 2131099657;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public static int alphabet_size = 2131165184;
			
			// aapt resource value: 0x7f070001
			public static int umeng_socialize_pad_window_height = 2131165185;
			
			// aapt resource value: 0x7f070002
			public static int umeng_socialize_pad_window_width = 2131165186;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int umeng_socialize_fav = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int umeng_socialize_more = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int umeng_socialize_share_music = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int umeng_socialize_share_pic = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int umeng_socialize_share_video = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int umeng_socialize_shareboard_item_background = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int umeng_socialize_title_back_bt = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int umeng_socialize_title_back_bt_normal = 2130837511;
			
			// aapt resource value: 0x7f020008
			public static int umeng_socialize_title_back_bt_selected = 2130837512;
			
			// aapt resource value: 0x7f020009
			public static int umeng_socialize_title_right_bt = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public static int umeng_socialize_title_right_bt_normal = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public static int umeng_socialize_title_right_bt_selected = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public static int umeng_socialize_wechat = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public static int umeng_socialize_window_shadow_pad = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public static int umeng_socialize_wxcircle = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public static int umeng_socialize_x_button = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090004
			public static int progress_bar_parent = 2131296260;
			
			// aapt resource value: 0x7f090001
			public static int umeng_socialize_follow = 2131296257;
			
			// aapt resource value: 0x7f090002
			public static int umeng_socialize_follow_check = 2131296258;
			
			// aapt resource value: 0x7f090008
			public static int umeng_socialize_follow_layout = 2131296264;
			
			// aapt resource value: 0x7f09000a
			public static int umeng_socialize_location_ic = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public static int umeng_socialize_location_progressbar = 2131296267;
			
			// aapt resource value: 0x7f09000c
			public static int umeng_socialize_share_at = 2131296268;
			
			// aapt resource value: 0x7f090007
			public static int umeng_socialize_share_bottom_area = 2131296263;
			
			// aapt resource value: 0x7f090011
			public static int umeng_socialize_share_edittext = 2131296273;
			
			// aapt resource value: 0x7f09000d
			public static int umeng_socialize_share_image = 2131296269;
			
			// aapt resource value: 0x7f090009
			public static int umeng_socialize_share_location = 2131296265;
			
			// aapt resource value: 0x7f09000e
			public static int umeng_socialize_share_previewImg = 2131296270;
			
			// aapt resource value: 0x7f090010
			public static int umeng_socialize_share_previewImg_progressbar = 2131296272;
			
			// aapt resource value: 0x7f09000f
			public static int umeng_socialize_share_previewImg_remove = 2131296271;
			
			// aapt resource value: 0x7f090005
			public static int umeng_socialize_share_root = 2131296261;
			
			// aapt resource value: 0x7f090006
			public static int umeng_socialize_share_titlebar = 2131296262;
			
			// aapt resource value: 0x7f090012
			public static int umeng_socialize_share_word_num = 2131296274;
			
			// aapt resource value: 0x7f090013
			public static int umeng_socialize_shareboard_image = 2131296275;
			
			// aapt resource value: 0x7f090014
			public static int umeng_socialize_shareboard_pltform_name = 2131296276;
			
			// aapt resource value: 0x7f090015
			public static int umeng_socialize_title_bar_leftBt = 2131296277;
			
			// aapt resource value: 0x7f090016
			public static int umeng_socialize_title_bar_middleTv = 2131296278;
			
			// aapt resource value: 0x7f090017
			public static int umeng_socialize_title_bar_middle_tab = 2131296279;
			
			// aapt resource value: 0x7f09001a
			public static int umeng_socialize_title_bar_rightBt = 2131296282;
			
			// aapt resource value: 0x7f09001b
			public static int umeng_socialize_title_bar_rightBt_progress = 2131296283;
			
			// aapt resource value: 0x7f090018
			public static int umeng_socialize_title_middle_left = 2131296280;
			
			// aapt resource value: 0x7f090019
			public static int umeng_socialize_title_middle_right = 2131296281;
			
			// aapt resource value: 0x7f090000
			public static int umeng_socialize_titlebar = 2131296256;
			
			// aapt resource value: 0x7f090003
			public static int webView = 2131296259;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int umeng_socialize_oauth_dialog = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int umeng_socialize_post_share = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int umeng_socialize_shareboard_item = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int umeng_socialize_titile_bar = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public static int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public static int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public static int pull_to_refresh_pull_label = 2131034114;
			
			// aapt resource value: 0x7f050004
			public static int pull_to_refresh_refreshing_label = 2131034116;
			
			// aapt resource value: 0x7f050003
			public static int pull_to_refresh_release_label = 2131034115;
			
			// aapt resource value: 0x7f050005
			public static int pull_to_refresh_tap_label = 2131034117;
			
			// aapt resource value: 0x7f050038
			public static int umeng_example_home_btn_plus = 2131034168;
			
			// aapt resource value: 0x7f050009
			public static int umeng_socialize_back = 2131034121;
			
			// aapt resource value: 0x7f05003b
			public static int umeng_socialize_cancel_btn_str = 2131034171;
			
			// aapt resource value: 0x7f050007
			public static int umeng_socialize_comment = 2131034119;
			
			// aapt resource value: 0x7f050008
			public static int umeng_socialize_comment_detail = 2131034120;
			
			// aapt resource value: 0x7f05003a
			public static int umeng_socialize_content_hint = 2131034170;
			
			// aapt resource value: 0x7f05000b
			public static int umeng_socialize_friends = 2131034123;
			
			// aapt resource value: 0x7f05003d
			public static int umeng_socialize_img_des = 2131034173;
			
			// aapt resource value: 0x7f050016
			public static int umeng_socialize_login = 2131034134;
			
			// aapt resource value: 0x7f050015
			public static int umeng_socialize_login_qq = 2131034133;
			
			// aapt resource value: 0x7f05003f
			public static int umeng_socialize_mail = 2131034175;
			
			// aapt resource value: 0x7f050011
			public static int umeng_socialize_msg_hor = 2131034129;
			
			// aapt resource value: 0x7f050010
			public static int umeng_socialize_msg_min = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public static int umeng_socialize_msg_sec = 2131034127;
			
			// aapt resource value: 0x7f05000a
			public static int umeng_socialize_near_At = 2131034122;
			
			// aapt resource value: 0x7f050006
			public static int umeng_socialize_network_break_alert = 2131034118;
			
			// aapt resource value: 0x7f05000c
			public static int umeng_socialize_send = 2131034124;
			
			// aapt resource value: 0x7f05003c
			public static int umeng_socialize_send_btn_str = 2131034172;
			
			// aapt resource value: 0x7f05003e
			public static int umeng_socialize_share = 2131034174;
			
			// aapt resource value: 0x7f050014
			public static int umeng_socialize_share_content = 2131034132;
			
			// aapt resource value: 0x7f050041
			public static int umeng_socialize_sina = 2131034177;
			
			// aapt resource value: 0x7f050040
			public static int umeng_socialize_sms = 2131034176;
			
			// aapt resource value: 0x7f050037
			public static int umeng_socialize_text_add_custom_platform = 2131034167;
			
			// aapt resource value: 0x7f050052
			public static int umeng_socialize_text_alipay_key = 2131034194;
			
			// aapt resource value: 0x7f050018
			public static int umeng_socialize_text_authorize = 2131034136;
			
			// aapt resource value: 0x7f050017
			public static int umeng_socialize_text_choose_account = 2131034135;
			
			// aapt resource value: 0x7f05001c
			public static int umeng_socialize_text_comment_hint = 2131034140;
			
			// aapt resource value: 0x7f050033
			public static int umeng_socialize_text_douban_key = 2131034163;
			
			// aapt resource value: 0x7f050045
			public static int umeng_socialize_text_evernote_key = 2131034181;
			
			// aapt resource value: 0x7f050047
			public static int umeng_socialize_text_facebook_key = 2131034183;
			
			// aapt resource value: 0x7f050050
			public static int umeng_socialize_text_flickr_key = 2131034192;
			
			// aapt resource value: 0x7f05004d
			public static int umeng_socialize_text_foursquare_key = 2131034189;
			
			// aapt resource value: 0x7f05001d
			public static int umeng_socialize_text_friend_list = 2131034141;
			
			// aapt resource value: 0x7f050054
			public static int umeng_socialize_text_googleplus_key = 2131034196;
			
			// aapt resource value: 0x7f050049
			public static int umeng_socialize_text_instagram_key = 2131034185;
			
			// aapt resource value: 0x7f050053
			public static int umeng_socialize_text_kakao_key = 2131034195;
			
			// aapt resource value: 0x7f050044
			public static int umeng_socialize_text_laiwangdynamic_key = 2131034180;
			
			// aapt resource value: 0x7f05004f
			public static int umeng_socialize_text_line_key = 2131034191;
			
			// aapt resource value: 0x7f05004c
			public static int umeng_socialize_text_linkedin_key = 2131034188;
			
			// aapt resource value: 0x7f05002c
			public static int umeng_socialize_text_loading_message = 2131034156;
			
			// aapt resource value: 0x7f05001b
			public static int umeng_socialize_text_login_fail = 2131034139;
			
			// aapt resource value: 0x7f050055
			public static int umeng_socialize_text_more_key = 2131034197;
			
			// aapt resource value: 0x7f05004a
			public static int umeng_socialize_text_pinterest_key = 2131034186;
			
			// aapt resource value: 0x7f05004b
			public static int umeng_socialize_text_pocket_key = 2131034187;
			
			// aapt resource value: 0x7f050030
			public static int umeng_socialize_text_qq_key = 2131034160;
			
			// aapt resource value: 0x7f050031
			public static int umeng_socialize_text_qq_zone_key = 2131034161;
			
			// aapt resource value: 0x7f050032
			public static int umeng_socialize_text_renren_key = 2131034162;
			
			// aapt resource value: 0x7f05002f
			public static int umeng_socialize_text_sina_key = 2131034159;
			
			// aapt resource value: 0x7f05002d
			public static int umeng_socialize_text_tencent_key = 2131034157;
			
			// aapt resource value: 0x7f05001f
			public static int umeng_socialize_text_tencent_no_connection = 2131034143;
			
			// aapt resource value: 0x7f050022
			public static int umeng_socialize_text_tencent_no_install = 2131034146;
			
			// aapt resource value: 0x7f050020
			public static int umeng_socialize_text_tencent_oauth_login_fail = 2131034144;
			
			// aapt resource value: 0x7f050021
			public static int umeng_socialize_text_tencent_version_no_match = 2131034145;
			
			// aapt resource value: 0x7f050051
			public static int umeng_socialize_text_tumblr_key = 2131034193;
			
			// aapt resource value: 0x7f050048
			public static int umeng_socialize_text_twitter_key = 2131034184;
			
			// aapt resource value: 0x7f05001a
			public static int umeng_socialize_text_ucenter = 2131034138;
			
			// aapt resource value: 0x7f050019
			public static int umeng_socialize_text_unauthorize = 2131034137;
			
			// aapt resource value: 0x7f05001e
			public static int umeng_socialize_text_visitor = 2131034142;
			
			// aapt resource value: 0x7f050023
			public static int umeng_socialize_text_waitting = 2131034147;
			
			// aapt resource value: 0x7f05002b
			public static int umeng_socialize_text_waitting_message = 2131034155;
			
			// aapt resource value: 0x7f050028
			public static int umeng_socialize_text_waitting_qq = 2131034152;
			
			// aapt resource value: 0x7f050029
			public static int umeng_socialize_text_waitting_qzone = 2131034153;
			
			// aapt resource value: 0x7f05002a
			public static int umeng_socialize_text_waitting_redirect = 2131034154;
			
			// aapt resource value: 0x7f050039
			public static int umeng_socialize_text_waitting_share = 2131034169;
			
			// aapt resource value: 0x7f050024
			public static int umeng_socialize_text_waitting_weixin = 2131034148;
			
			// aapt resource value: 0x7f050025
			public static int umeng_socialize_text_waitting_weixin_circle = 2131034149;
			
			// aapt resource value: 0x7f050026
			public static int umeng_socialize_text_waitting_yixin = 2131034150;
			
			// aapt resource value: 0x7f050027
			public static int umeng_socialize_text_waitting_yixin_circle = 2131034151;
			
			// aapt resource value: 0x7f050035
			public static int umeng_socialize_text_weixin_circle_key = 2131034165;
			
			// aapt resource value: 0x7f050036
			public static int umeng_socialize_text_weixin_fav_key = 2131034166;
			
			// aapt resource value: 0x7f050034
			public static int umeng_socialize_text_weixin_key = 2131034164;
			
			// aapt resource value: 0x7f05002e
			public static int umeng_socialize_text_wenxin_fav = 2131034158;
			
			// aapt resource value: 0x7f05004e
			public static int umeng_socialize_text_whatsapp_key = 2131034190;
			
			// aapt resource value: 0x7f050046
			public static int umeng_socialize_text_ydnote_key = 2131034182;
			
			// aapt resource value: 0x7f050042
			public static int umeng_socialize_text_yixin_key = 2131034178;
			
			// aapt resource value: 0x7f050043
			public static int umeng_socialize_text_yixincircle_key = 2131034179;
			
			// aapt resource value: 0x7f05000d
			public static int umeng_socialize_tip_blacklist = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public static int umeng_socialize_tip_loginfailed = 2131034126;
			
			// aapt resource value: 0x7f050012
			public static int umeng_socialize_ucenter_login_title_guide = 2131034130;
			
			// aapt resource value: 0x7f050013
			public static int umeng_socialize_ucenter_login_title_platform = 2131034131;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public static int ACPLDialog = 2131230720;
			
			// aapt resource value: 0x7f08000a
			public static int Theme_UMDefault = 2131230730;
			
			// aapt resource value: 0x7f080009
			public static int Theme_UMDialog = 2131230729;
			
			// aapt resource value: 0x7f080002
			public static int umeng_socialize_action_bar_item_im = 2131230722;
			
			// aapt resource value: 0x7f080003
			public static int umeng_socialize_action_bar_item_tv = 2131230723;
			
			// aapt resource value: 0x7f080001
			public static int umeng_socialize_action_bar_itemlayout = 2131230721;
			
			// aapt resource value: 0x7f080007
			public static int umeng_socialize_dialog_anim_fade = 2131230727;
			
			// aapt resource value: 0x7f080006
			public static int umeng_socialize_dialog_animations = 2131230726;
			
			// aapt resource value: 0x7f08000b
			public static int umeng_socialize_divider = 2131230731;
			
			// aapt resource value: 0x7f08000d
			public static int umeng_socialize_edit_padding = 2131230733;
			
			// aapt resource value: 0x7f08000c
			public static int umeng_socialize_list_item = 2131230732;
			
			// aapt resource value: 0x7f080005
			public static int umeng_socialize_popup_dialog = 2131230725;
			
			// aapt resource value: 0x7f080004
			public static int umeng_socialize_popup_dialog_anim = 2131230724;
			
			// aapt resource value: 0x7f080008
			public static int umeng_socialize_shareboard_animation = 2131230728;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
